# Generated by Django 5.2.2 on 2025-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_pdfqa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PdfQA',
        ),
    ]
