# Generated by Django 5.2.2 on 2025-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_remove_pdfquestionanswer_pdf_name_uploadedpdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfquestionanswer',
            name='pdf',
        ),
        migrations.AddField(
            model_name='pdfquestionanswer',
            name='pdf_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
    ]
