# Generated by Django 5.2.2 on 2025-07-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_pdfquestionanswer_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
